apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  template:
    spec:
      containers:
      - name: demo
        env:
          - name: SPRING_APPLICATION_JSON
            value: '{"logging.level.org.springframework.boot.context.config": "trace"}'
