apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: localhost:5000/apps/demo
    buildpacks:
      builder: localhost:5000/packs/java
      dependencies:
        paths:
          - pom.xml
          - src/main/resources
          - target/classes
    sync:
      manual:
      - src: "target/classes/**/*"
        dest: /workspace/BOOT-INF/classes
        strip: target/classes/
deploy:
  kustomize:
    paths:
    - k8s/simple

profiles:
  - name: dev
    deploy:
      kustomize:
       paths:
       - k8s/dev
  - name: prod
    deploy:
      kustomize:
       paths:
       - k8s/prod
