apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  template:
    spec:
      containers:
      - name: demo
        command:
            - "/cnb/lifecycle/launcher"
            - "dev"