apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  template:
    spec:
      containers:
      - name: demo
        volumeMounts:
        - name: mysql
          mountPath: /config/bindings/mysql/meta
        env:
        - name: SPRING_CONFIG_IMPORTS
          value: configtree:/config/bindings/
      volumes:
      - name: mysql
        configMap:
          name: mysql-tree
